
- name: download nodebrew
  sudo: yes
  command: wget git.io/nodebrew -P /var/tmp

- name: install nodebrew
  command: perl /var/tmp/nodebrew setup

- name: install node.js latest
  ignore_errors: True
  shell: bash -lc "nodebrew install-binary latest"

- name: use node.js version
  shell: bash -lc "nodebrew use latest"

- name: install chromedriver
  shell: bash -lc "npm install -g chromedriver"


