
- name: download GPG key
  raw: sudo wget -q -O - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo apt-key add -

- name: add repository
  raw: sudo sh -c "echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list"

- name: install xvfb firefox
  apt: pkg={{item}} state=latest
  with_items:
    - xvfb
    - firefox

- name: install JRE
  apt: pkg={{item}} state=latest
  with_items:
    - openjdk-8-jre

- name: update apt-get
  raw: sudo apt-get update -y

- name: install google-chrome-stable
  apt: pkg={{item}} state=latest
  with_items:
    - google-chrome-stable
